### ISSUE TITLE
Upgrade Flask dependency

### ISSUE THREAD

**Issue by kaitj** [afids/afids-validator#225]
## The problem

Some package dependencies have upgraded and introduced new, breaking changes (e.g. see #224, where version used had to be reverted and pinned). Long term, Flask is also at `3.0` at the time of writing this issue, while the app is using `2.x`. Long-term, an update should be made to the new version to resolve these dependency issues.

## Environment

* Browser (with version)
* Dropdown menu option
* File uploaded (if applicable)

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/ISSUE_TEMPLATE.md)_

**Comment by kaitj** [comment]
Started to work on this to update all dependencies. Almsot complete, but need to update instructions for testing development.

### Tasks:

- [ ] Get database working again
- [ ] Get sandbox orcid oauth working
- [ ] Enable ability to read from `.env` file -> currently set directly in environment (both dev and prod)
- [ ] Update developer setup / testing instructions
